server.port=8081
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BASIS;encrypt=true;trustServerCertificate=true
spring.datasource.username=admin
spring.datasource.password=admin

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

####FINAL
#server.port = 8081                
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BASIS;encrypt=true;trustServerCertificate=true
#spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
#spring.datasource.username=admin
#spring.datasource.password=admin  
#spring.datasource.driver-className=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true                                                      
#spring.jpa.properties.hibernate.dspring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2014Dialect       ialect= org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto= upspring.jpa.hibernate.ddl-auto =ddl-auto                                       date                                          
###DEV
#spring.datasource.url = jdbc:sqlserver://localhost:1433;databaseName=BASIS;encrypt=true;trustServerCertificate=true
#spring.datasource.username=admin
#spring.datasource.password=admin
#server.port = 8081
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
              

###TEST
##habititar acesso ao h2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
###configurações do h2
#spring.datasource.platform=h2
#spring.datasource.url=jdbc:h2:~/test
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.driver
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true






